config/routes.rb
Rails.application.routes.draw do
  get 'control_users/index'

  devise_for :users
  resources :amercements
  resources :loans
  resources :copies
  resources :evaluations
  resources :books
  resources :authors
  resources :publishers

  root 'welcome#index'

end

app/models/evaluation.rb
class Evaluation < ActiveRecord::Base
end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController
  before_action :set_evaluation, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

  # GET /evaluations
  # GET /evaluations.json
  def index
    @evaluations = Evaluation.all
  end

  # GET /evaluations/1
  # GET /evaluations/1.json
  def show
  end

  # GET /evaluations/new
  def new
    @evaluation = Evaluation.new
  end

  # GET /evaluations/1/edit
  def edit
  end

  # POST /evaluations
  # POST /evaluations.json
  def create
    @evaluation = Evaluation.new(evaluation_params)

    respond_to do |format|
      if @evaluation.save
        format.html { redirect_to @evaluation, notice: 'Evaluation was successfully created. If you want to delet or edit your evaluation, talk to an attendant.' }
        format.json { render :show, status: :created, location: @evaluation }
      else
        format.html { render :new }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evaluations/1
  # PATCH/PUT /evaluations/1.json
  def update
    respond_to do |format|
      if @evaluation.update(evaluation_params)
        format.html { redirect_to @evaluation, notice: 'Evaluation was successfully updated.' }
        format.json { render :show, status: :ok, location: @evaluation }
      else
        format.html { render :edit }
        format.json { render json: @evaluation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evaluations/1
  # DELETE /evaluations/1.json
  def destroy
    @evaluation.destroy
    respond_to do |format|
      format.html { redirect_to evaluations_url, notice: 'Evaluation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evaluation
      @evaluation = Evaluation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evaluation_params
      params.require(:evaluation).permit(:id_book, :id_client, :text, :grade)
    end
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/views/evaluations/_form.html.erb
<%= form_for(@evaluation) do |f| %>
  <% if @evaluation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evaluation.errors.count, "error") %> prohibited this evaluation from being saved:</h2>

      <ul>
      <% @evaluation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_book %><br>
    <%= f.number_field :id_book %>
  </div>
  <div class="field">
    <%= f.label :id_client %><br>
    <%= f.number_field :id_client %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :grade %><br>
    <%= f.number_field :grade %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/evaluations/edit.html.erb
<h1>Editing Evaluation</h1>

<%= render 'form' %>

<%= link_to 'Show', @evaluation %> |
<%= link_to 'Back', evaluations_path %>

app/views/evaluations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Evaluations</h1>

<table border=1>
  <thead>
    <tr>
			<th>Id</th>
      <th>Id book</th>
      <th>Id client</th>
      <th>Grade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @evaluations.each do |evaluation| %>
      <tr>
				<td><%= evaluation.id %></td>
        <td><%= evaluation.id_book %></td>
        <td><%= evaluation.id_client %></td>
        <td><%= evaluation.grade %></td>
        <td><%= link_to 'Show', evaluation %></td>
				<% if policy(@evaluations).index? %>
      	  <td><%= link_to 'Edit', edit_evaluation_path(evaluation) %></td>
        	<td><%= link_to 'Destroy', evaluation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if policy(@evaluations).index? || current_user.client?%>
	<%= link_to 'New Evaluation', new_evaluation_path %>
<% end %>
<%= link_to 'Back', root_path %>

app/views/evaluations/new.html.erb
<h1>New Evaluation</h1>

<%= render 'form' %>

<%= link_to 'Back', evaluations_path %>

app/views/evaluations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id book:</strong>
  <%= @evaluation.id_book %>
</p>

<p>
  <strong>Id client:</strong>
  <%= @evaluation.id_client %>
</p>

<p>
  <strong>Text:</strong>
  <%= @evaluation.text %>
</p>

<p>
  <strong>Grade:</strong>
  <%= @evaluation.grade %>
</p>

<br>
<%= link_to 'Back', evaluations_path %>