config/routes.rb
Rails.application.routes.draw do
  get 'control_users/index'

  devise_for :users
  resources :amercements
  resources :loans
  resources :copies
  resources :evaluations
  resources :books
  resources :authors
  resources :publishers

  root 'welcome#index'

end

app/models/copy.rb
class Copy < ActiveRecord::Base
end

app/controllers/copies_controller.rb
class CopiesController < ApplicationController
  before_action :set_copy, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]	

  # GET /copies
  # GET /copies.json
  def index
    @copies = Copy.all
  end

  # GET /copies/1
  # GET /copies/1.json
  def show
  end

  # GET /copies/new
  def new
    @copy = Copy.new
  end

  # GET /copies/1/edit
  def edit
  end

  # POST /copies
  # POST /copies.json
  def create
    @copy = Copy.new(copy_params)

    respond_to do |format|
      if @copy.save
        format.html { redirect_to @copy, notice: 'Copy was successfully created.' }
        format.json { render :show, status: :created, location: @copy }
      else
        format.html { render :new }
        format.json { render json: @copy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /copies/1
  # PATCH/PUT /copies/1.json
  def update
    respond_to do |format|
      if @copy.update(copy_params)
        format.html { redirect_to @copy, notice: 'Copy was successfully updated.' }
        format.json { render :show, status: :ok, location: @copy }
      else
        format.html { render :edit }
        format.json { render json: @copy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /copies/1
  # DELETE /copies/1.json
  def destroy
    @copy.destroy
    respond_to do |format|
      format.html { redirect_to copies_url, notice: 'Copy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_copy
      @copy = Copy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def copy_params
      params.require(:copy).permit(:id_book, :copyStatus)
    end
end

app/helpers/copies_helper.rb
module CopiesHelper
end

app/views/copies/_form.html.erb
<%= form_for(@copy) do |f| %>
  <% if @copy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@copy.errors.count, "error") %> prohibited this copy from being saved:</h2>

      <ul>
      <% @copy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_book %><br>
    <%= f.number_field :id_book %>
  </div>
  <div class="field">
    <%= f.label :copyStatus %><br>
    <%= f.text_field :copyStatus %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/copies/edit.html.erb
<h1>Editing Copy</h1>

<%= render 'form' %>

<%= link_to 'Show', @copy %> |
<%= link_to 'Back', copies_path %>

app/views/copies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Copies</h1>

<table border=1>
  <thead>
    <tr>
			<th>Id</th>
      <th>Id book</th>
      <th>Copystatus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @copies.each do |copy| %>
      <tr>
				<td><%= copy.id %></td>
        <td><%= copy.id_book %></td>
        <td><%= copy.copyStatus %></td>
        <td><%= link_to 'Show', copy %></td>
				<% if policy(@copies).index? %>
					<td><%= link_to 'Edit', edit_copy_path(copy) %></td>
        	<td><%= link_to 'Destroy', copy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if policy(@copies).index? %>
	<%= link_to 'New Copy', new_copy_path %>
<% end %>

<%= link_to 'Back', root_path %>

app/views/copies/new.html.erb
<h1>New Copy</h1>

<%= render 'form' %>

<%= link_to 'Back', copies_path %>

app/views/copies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id book:</strong>
  <%= @copy.id_book %>
</p>

<p>
  <strong>Copystatus:</strong>
  <%= @copy.copyStatus %>
</p>

<br>

<%= link_to 'Back', copies_path %>