config/routes.rb
Rails.application.routes.draw do
  get 'control_users/index'

  devise_for :users
  resources :amercements
  resources :loans
  resources :copies
  resources :evaluations
  resources :books
  resources :authors
  resources :publishers

  root 'welcome#index'

end

app/models/loan.rb
class Loan < ActiveRecord::Base
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]	

  # GET /loans
  # GET /loans.json
  def index
    @loans = Loan.all
  end

  # GET /loans/1
  # GET /loans/1.json
  def show
  end

  # GET /loans/new
  def new
    @loan = Loan.new
  end

  # GET /loans/1/edit
  def edit
  end

  # POST /loans
  # POST /loans.json
  def create
    @loan = Loan.new(loan_params)

    respond_to do |format|
      if @loan.save
        format.html { redirect_to @loan, notice: 'Loan was successfully created.' }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /loans/1
  # PATCH/PUT /loans/1.json
  def update
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: 'Loan was successfully updated.' }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /loans/1
  # DELETE /loans/1.json
  def destroy
    @loan.destroy
    respond_to do |format|
      format.html { redirect_to loans_url, notice: 'Loan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def loan_params
      params.require(:loan).permit(:id_copy, :id_client, :id_attendant, :startDate, :expectedDate, :deliveryDate, :loanStatus)
    end
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/_form.html.erb
<%= form_for(@loan) do |f| %>
  <% if @loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
      <% @loan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_copy %><br>
    <%= f.number_field :id_copy %>
  </div>
  <div class="field">
    <%= f.label :id_client %><br>
    <%= f.number_field :id_client %>
  </div>
  <div class="field">
    <%= f.label :id_attendant %><br>
    <%= f.number_field :id_attendant %>
  </div>
  <div class="field">
    <%= f.label :startDate %><br>
    <%= f.datetime_select :startDate %>
  </div>
  <div class="field">
    <%= f.label :expectedDate %><br>
    <%= f.datetime_select :expectedDate %>
  </div>
  <div class="field">
    <%= f.label :deliveryDate %><br>
    <%= f.datetime_select :deliveryDate %>
  </div>
  <div class="field">
    <%= f.label :loanStatus %><br>
    <%= f.text_field :loanStatus %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/loans/edit.html.erb
<h1>Editing Loan</h1>

<%= render 'form' %>

<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loans_path %>

app/views/loans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Loans</h1>

<table border=1>
  <thead>
    <tr>
			<th>Id</th>
      <th>Id copy</th>
      <th>Id client</th>
      <th>Id attendant</th>
      <th>Start date</th>
      <th>Expected date</th>
      <th>Delivery date</th>
      <th>Loan status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @loans.each do |loan| %>
      <tr>
				<td><center><%= loan.id %></center></td>
        <td><center><%= loan.id_copy %></center></td>
        <td><center><%= loan.id_client %></center></td>
        <td><center><%= loan.id_attendant %></center></td>
        <td><center><%= loan.startDate %></center></td>
        <td><center><%= loan.expectedDate %></center></td>
        <td><center><%= loan.deliveryDate %></center></td>
        <td><center><%= loan.loanStatus %></center></td>
        <td><%= link_to 'Show', loan %></td>
				<% if policy(@loans).index? %>
	        <td><%= link_to 'Edit', edit_loan_path(loan) %></td>
        <td><%= link_to 'Destroy', loan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if policy(@loans).index? %>
	<%= link_to 'New Loan', new_loan_path %>
<% end %>

<%= link_to 'Back', root_path %>

app/views/loans/new.html.erb
<h1>New Loan</h1>

<%= render 'form' %>

<%= link_to 'Back', loans_path %>

app/views/loans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id copy:</strong>
  <%= @loan.id_copy %>
</p>

<p>
  <strong>Id client:</strong>
  <%= @loan.id_client %>
</p>

<p>
  <strong>Id attendant:</strong>
  <%= @loan.id_attendant %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @loan.startDate %>
</p>

<p>
  <strong>Expecteddate:</strong>
  <%= @loan.expectedDate %>
</p>

<p>
  <strong>Deliverydate:</strong>
  <%= @loan.deliveryDate %>
</p>

<p>
  <strong>Loanstatus:</strong>
  <%= @loan.loanStatus %>
</p>

<br>

<%= link_to 'Back', loans_path %>